Palazzowebadmin/app/jackpot/__init__.py
# -*- encoding: utf-8 -*-

from flask import Blueprint

blueprint = Blueprint(
    'jackpot_blueprint',
    __name__,
    url_prefix='',
    template_folder='templates',
    static_folder='static'
)

Palazzowebadmin/app/jackpot/routes.py
from app import db, login_manager
from app.jackpot import blueprint
from app.base.forms import footerForm
from app.base.models import Footerdata
from flask import jsonify, render_template, redirect, request, url_for
from flask_login import login_required
from flask.helpers import flash
from datetime import date
from flask_login import (
    current_user,
    login_required,
    login_user,
    logout_user
)
import json
# ----------------------------- Jackpot info  -----------------------------#

@blueprint.route("/jackpot",methods=['GET', 'POST'])
@login_required
def jackpotinfo():
    jackpots= Footerdata.query.order_by(Footerdata.f_id).all()
    form = footerForm()
    return render_template('jackpots.html', jackpots = jackpots,form=form, segment='jackpots')

@blueprint.route("/jackpot/add",methods=['GET', 'POST'])
@login_required
def addjackpotinfo():
    name = request.form['name']
    value = request.form['value']
    jackpot                   = Footerdata(f_name = name,
                                            f_value = value,
                                            modifyby    = current_user.username
                                            )
    db.session.add(jackpot)
    db.session.flush()
    db.session.commit()
    flash('Data has been added!', 'success')
    return redirect(url_for('jackpot_blueprint.jackpotinfo'))

@blueprint.route("/jackpot/<int:id>/edit",methods=['GET', 'POST'])
@login_required
def editjackpotinfo(id):
    jackpot= Footerdata.query.get_or_404(id)
    name = request.form['name']
    value = request.form['value']
    jackpot.f_name = name
    jackpot.f_value = value
    jackpot.modifyday = date.today()
    jackpot.modifyby = current_user.username
    db.session.add(jackpot)
    db.session.commit()
    flash('The element has been updated.')
    return redirect(url_for('jackpot_blueprint.jackpotinfo'))

@blueprint.route("/jackpot/<int:id>/delete",methods=['GET', 'POST'])
@login_required
def deletejackpotinfo(id):
    jackpot=  Footerdata.query.get_or_404(id)
    db.session.delete(jackpot)
    db.session.commit()
    return redirect(url_for('jackpot_blueprint.jackpotinfo'))

@blueprint.route('/jackpot/<int:id>/changestatus',methods=['GET','POST'])
@login_required
def changejackpotstatus(id):
    try:
        data = request.form['status']
        jacpot = Footerdata.query.get_or_404(id)
        if data != '':
            if data =='y' and jacpot.status == True:
                jacpot.status = False
            elif data == 'y' and jacpot.status == False: 
                jacpot.status = True
            db.session.commit()
            db.session.remove()
            return redirect(url_for('jackpot_blueprint.jackpotinfo'))
        else:
            return render_template('page-500.html'), 500
    except:
        return render_template('page-500.html'), 500

@blueprint.route("/jackpot/update",methods=['GET', 'POST'])
def updatejackpot():
    if request.method == 'POST':
        id = request.values['id']
        value = request.values['value']
        json.loads(id)
        jackpot= Footerdata.query.get_or_404(id)
        jackpot.f_value = value
        jackpot.modifyday = date.today()
        jackpot.modifyby = 'auto requests'
        db.session.add(jackpot)
        db.session.commit()
        return jsonify({"success": True}), 200

Palazzowebadmin/app/jackpot/templates/jackpots.html
{% extends "layouts/base.html" %}

{% block title %} Jackpots Infomations {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}
    <div class="table-settings mb-4">
        {% for message in get_flashed_messages() %}
    <div class="alert alert-success">
        {{ message }}
    </div>
    {% endfor %}
      <div class="d-block mb-4 mb-md-0">
          <nav aria-label="breadcrumb">
              <ol class="breadcrumb breadcrumb-dark breadcrumb-transparent">
                  <li class="breadcrumb-item"><a href="{{url_for('admin_blueprint.statistic')}}"><span class="fas fa-home"></span></a></li>
                  <li class="breadcrumb-item active" aria-current="page"><a href="{{url_for('jackpot_blueprint.jackpotinfo')}}">Jackpots Infomations</a></li>
              </ol>
          </nav>
          <div class="d-flex justify-content-between w-100 flex-wrap">
              <div class="mb-3 mb-lg-0">
                  <h1 class="h4">Jackpots Infomations</h1>
                  <p class="mb-0"></p>
              </div>
             
          </div>
          <div>
        <div class="btn-toolbar dropdown">
            <div class="table-settings mb-4">
      <div class="row align-items-center justify-content-between">
          <div class="col col-md-6 col-lg-3 col-xl-4">
              <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center py-4">
                <div class="btn-toolbar dropdown">
                    <button class="btn btn-dark btn-sm me-2 dropdown-toggle" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <span class="fas fa-plus me-2"></span>Task
            </button>
            <div class="dropdown-menu dashboard-dropdown dropdown-menu-start mt-2 py-0">
                <a class="dropdown-item fw-normal rounded-top" data-bs-toggle="modal" data-bs-target="#addjackpot"><span class="fas fa-tasks"></span>Add New Jackpot</a>
                <div role="separator" class="dropdown-divider my-0"></div>
            </div>
                </div>
            </div>
        </div>
    </div>
                <div class="col-sm-4">
                    <div class="modal fade" id="addjackpot" tabindex="-1" role="dialog" aria-labelledby="addjackpot" aria-hidden="true">
                        <div class="modal-dialog modal-dialog-centered" role="document">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h2 class="h6 modal-title"></h2>
                                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                </div>
                                <div class="modal-body">
                                <form method="POST" action="{{url_for('jackpot_blueprint.addjackpotinfo')}}">
                                    {{ form.hidden_tag() }}
                                    {{ form.csrf_token }}
                                    <div class="row">
                                        <div class="col-12 mb-4">
                                            <div class="card shadow-sm text-center p-0">
                                                <div class="card-body pb-5">
                                                    <ul class="list-group list-group-flush">
                                                        <li class="list-group-item d-flex align-items-center justify-content-between px-0 border-bottom">
 <div>
                                                                <h3 class="h6 mb-1">Display status</h3>
                                                                <p class="small pe-4">Set as True to show on Application</p>
                                                            </div>
                                                            <div>
                                                                <div class="form-check form-switch">
                                                                    <input checked class="form-check-input" type="checkbox" id="user-notification-1">
                                                                    <label class="form-check-label" for="user-notification-1"></label>
                                                                </div>
                                                            </div>
                                                        </li>
                                                        <li class="list-group-item d-flex align-items-center justify-content-between px-0 border-bottom">
                                                            <div>
                                                                <div class="form-group" title="The name of Jackpotinfo.">
                                                                {{ form.name.label(class="form-control-label") }} 
                                                                    {% if form.name.errors %} 
                                                                        {{ form.name(class="form-control" ,type="number" ,placeholder="0",min="0") }}
                                                                        <div class="invalid-feedback">
                                                                            {% for error in form.name.errors %}
                                                                            <span>{{ error }}</span>
                                                                            {% endfor %}
                                                                        </div>
                                                                    {% else %} 
                                                                        {{ form.name(class="form-control form-control ",placeholder='Jackpotinfo name') }}
                                                                    {% endif %}
                                                                </div>
                                                            </div>
                                                            <div>
                                                                <div class="form-group" title="The Value of Jackpotinfo.">
                                                                {{ form.value.label(class="form-control-label") }} 
                                                                    {% if form.value.errors %} 
                                                                        {{ form.value(class="form-control form-control is-invalid") }}
                                                                        <div class="invalid-feedback">
                                                                            {% for error in form.value.errors %}
                                                                            <span>{{ error }}</span>
                                                                            {% endfor %}
                                                                        </div>
                                                                    {% else %} 
                                                                        {{ form.value(class="form-control form-control ",placeholder='Jackpotinfo Value') }}
                                                                    {% endif %}
                                                                </div>
                                                            </div>
                                                        </li>
                                                    
                                                    </ul>
                                                </div>
                                                </div>
                                        </div>
                                </div>
                                <div class="modal-footer">
                                {{form.submit(class="btn btn-secondary")}}
                                </div>
                                </form>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
          </div>
      </div>

      <div class="card border-light shadow-sm mb-4">
          <div class="card-body">
              <div class="table-responsive">
                  <table class="table table-centered table-nowrap mb-0 rounded">
                      <thead class="thead-light">
                          <tr>
                              <th class="border-0">#</th>
                              <th class="border-0">Name </th>
                              <th class="border-0">Value</th>
                              <th class="border-0">Modify Day</th>
                              <th class="border-0">Modify By</th>
                              <th class="border-0">Status</th>
                              <th class="border-0">Edit</th>
                          </tr>
                      </thead>
                      <tbody>
                      {%for jackpot in jackpots%}
                          <!-- Item -->
                          <tr>
                              <td class="border-0"><a href="#" class="text-primary fw-bold">#</a> </td>
                              
                              <td class="border-0 fw-bold"><span class="icon icon-xs icon-gray w-30"><span class="fas fa-globe-europe"></span></span>
                              {%if jackpot.status%}
                      <span class="fw-bold text-success">{{jackpot.f_name}}</span>
                      {%else%}
                      <span class="fw-bold text-warning">{{jackpot.f_name}}</span>
                      {%endif%}
                              </td>
                              <td class="border-0">
                                  {{jackpot.f_value}}
                              </td>
                              <td class="border-0">
                                {{jackpot.modifyday}}
                              </td>
                              <td class="border-0">
                                {{jackpot.modifyby}}
                              </td>
                              <td class="border-0">
                                          <div class="small fw-bold">
                                          {%if jackpot.status%}
                                        <span class="fw-bold text-success">Visible</span>
                                        {%else%}
                                        <span class="fw-bold text-warning">Invisible</span>
                                            {%endif%}    
                                          </div>
                              </td>
                              <td class="border-0 text-success">
                                <div class="btn-group">
                                    <button class="btn btn-link text-dark dropdown-toggle dropdown-toggle-split m-0 p-0" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        <span class="icon icon-sm">
                                            <span class="fas fa-ellipsis-h icon-dark"></span>
                                        </span>
                                        <span class="sr-only">Toggle Dropdown</span>
                                    </button>
                                    <div class="dropdown-menu py-0">
                                        <a class="dropdown-item" href="#"  data-bs-toggle="modal" data-bs-target="#edit{{jackpot.f_id}}"><span class="fas fa-edit me-2"></span>Edit Jackpot</a>
                                        <a class="dropdown-item" href="#" data-bs-toggle="modal" data-bs-target="#status{{jackpot.f_id}}"><span class="fas fa-check-square"></span>
                                        {%if jackpot.status%}
                                            <span class="fw-bold text-warning">Disable Jackpot</span>
                                            {%else%}
                                            <span class="fw-bold text-success">Enable Jackpot</span>
                                            {%endif%}   
                                        </a>
                                        
                                        <a class="dropdown-item text-danger rounded-bottom" href="#" data-bs-toggle="modal" data-bs-target="#remove{{jackpot.f_id}}"><span class="fas fa-trash-alt me-2"></span>Remove</a>
                                        </div>
                                    </div>
                              </td>
                          </tr>
                        {% include 'formfile.html' %}
                        {%endfor%}
                      </tbody>
                  </table>
              </div>
          </div>
      </div>
{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}